name: Security Checks

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'requirements*.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'requirements*.txt'
  workflow_dispatch:

env:
  PIP_CACHE_DIR: ~/.cache/pip
  PYTHON_VERSION: '3.11'

jobs:
  security:
    name: Run Security Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test,all]"
    
    - name: Run security checks
      run: |
        make check-security
